### PR TITLE
Create it.js

### PR DESCRIPTION
**Pull request by raffaelone**
Italian translation

### CODE REVIEW

**Comment by te-online** [comment]
Hey @raffaelone 👋 
Thanks for your contribution! Highly appreciated 😊 

Would you mind adding the corresponding `.json` file with the same translation? 🙇

**Comment by raffaelone** [comment]
Done. New Pull Create it.json

**Comment by te-online** [comment]
Thanks! 🙌 The [JSON validator](https://duckduckgo.com/?q=json+validator&t=ffab&ia=answer) tells me, there's a `}` missing in the very end of the `.json` file. If you add that, we're ready to merge. 

No need to create a new Pull Request, by the way – the changes you do to the same branch are reflected here automatically 😉

**Comment by raffaelone** [comment]
Sorry, I didn't notice. I corrected the missing } at the end of .json file.

**Comment by te-online** [comment]
Perfect – translation will be in the next release. Will prepare that soon 👍

**Pull request merged**
